version: "3.2"
services:
        server:
                build:
                        context: "../../"
                        dockerfile: "examples/social-net/server/Dockerfile"
                command: ["npm", "start"]
                ports:
                        - 7001:8080
        client:
                build:
                        context: "../../"
                        dockerfile: "examples/social-net/client/Dockerfile"
                command: ["./node_modules/.bin/ng", "serve", "--host", "0.0.0.0"]
                environment:
                        - SERVER_PORT=7001
                ports:
                        - 7000:4200
