version: "3.2"
services:
        server:
                build:
                        context: "../../"
                        dockerfile: "examples/simple-counter/server/Dockerfile"
                command: ["npm", "start"]
                ports:
                        - 7001:8080
        client:
                build:
                        context: "../../"
                        dockerfile: "examples/simple-counter/client/Dockerfile"
                command: ["./node_modules/.bin/ng", "serve", "--host", "0.0.0.0"]
                volumes:
                        - ./client/src:/usr/app/examples/counter/client/src
                environment:
                        - SERVER_PORT=7001
                ports:
                        - 7000:4200
